### ISSUE TITLE
Inc logo bottom margin on desktop 

### ISSUE THREAD

**Issue by madimadx** [CUHackers/cuhackit_2019#23]
Maybe scale down the clock a little to make this work. The logo needs about the same amount of margin that's on the top of it between the bottom of the logo and clock.

**Comment by acarrab** [comment]
@madimadx 

![image](https://user-images.githubusercontent.com/8878541/35747794-aab6e9b8-0819-11e8-8da8-2e57fbf824a6.png)

Hey, I think they are the same distance. Do you mean from the blue text within the clock then? Or do you mean when we are really zoomed out? 

![image](https://user-images.githubusercontent.com/8878541/35747876-0246d17a-081a-11e8-8628-74e8a0c7cc23.png)


I don't think we should ever be that far zoomed out since we can press ctrl+ on the computer. Let me know what you think!

**Comment by madimadx** [comment]
This is fine.

**Comment by madimadx** [comment]
Only a problem when you squish browser horizontally.
<img width="1171" alt="screen shot 2018-02-28 at 12 48 37 am" src="https://user-images.githubusercontent.com/18021093/36771978-5ae3109e-1c21-11e8-81cd-db853bc0c685.png">
If you think no one will do that, don't worry about it and close this issue.
